config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Defines the root path route ("/")
  root to: "cycles#index"
  # Defines custom routes
  resources :cycles
  resources :models, only: [
    :show,
    :new,
    :create,
    :edit,
    :update,
    :destroy
  ]
  resources :brands, only: [
    :show,
    :new,
    :create,
    :edit,
    :update,
    :destroy
  ]
  resources :licenses, only: [
    :show,
    :new,
    :create,
    :edit,
    :update,
    :destroy
  ]
end

app/models/cycle.rb
class Cycle < ApplicationRecord
  belongs_to :user
  belongs_to :license
  belongs_to :brand
  belongs_to :model
  has_many :bookings

  validates :title,
            presence: {
              message: "Vous devez donner un titre à votre annonce."
            },
            length: {
              in: 15..80,
              too_short: "Soyez un peu plus précis : c'est la première chose que vos potentiels acheteurs vont voir.",
              too_long: "C'est un peu trop long : gardez les détails pour la description."
            }
  validates :description,
            presence: {
              message: "Vous devez donner un titre à votre annonce."
            },
            length: {
              in: 80..1000,
              too_short: "Dites-en plus à vos potentiels acheteurs : pourquoi la vendez-vous ? En quel état est-elle ?",
              too_long: "C'est un peu trop long : concentrez-vous sur les informations essentielles pour l'acheteur."
            }
  validates :color,
            presence: {
              message: "Choisissez la couleur qui décrit le mieux votre moto."
            }
  validates :general_state,
            presence: {
              message: "Choisissez l'option qui décrit le mieux l'état général de votre moto."
            }
  validates :location,
            presence: {
              message: "Indiquez où les acheteurs peuvent récupérer la moto."
            }
  validates :price,
            presence: {
              message: "Indiquez le prix auquel vous souhaitez vendre votre moto."
            }
  validates :release_date,
            presence: {
              message: "Indiquez quand votre moto est arrivée sur le marché."
            }
  validates :user_combined_range,
            presence: {
              message: "Indiquez l'autonomie réelle de votre moto - celle que vous avez constaté, pas celle donnée par le constructeur."
            },
            numericality: {
              in: 10..800,
              too_short: "L'autonomie réelle est probablement un peu trop faible. Combien de kilomètres pouvez-vous rouler avec votre moto habituellement ?",
              too_long: "L'autonomie réelle est probablement inférieur à ça. Combien de kilomètres pouvez-vous rouler avec votre moto habituellement ?"
            }
  validates :kilometrage,
            presence: {
              message: "Indiquez combien de kilomètres le compteur affiche."
            }
  validates :release_date,
            presence: {
              message: "Indiquez l'état de vos pneumatiques en quelques mots."
            }
  validates :battery_soh,
            presence: {
              message: "Indiquez l'état de santé de votre batterie, comme indiqué sur le tableau de bord."
            },
            numericality: {
              in: 0..100,
              too_short: "L'état de santé de votre batterie se mesure en % - il ne peut pas être négatif.",
              too_long: "L'état de santé de votre batterie se mesure en % - il ne peut pas être supérieur à 100."
            }
  validates :nb_of_owners,
            presence: {
              message: "Inscrivez 1 si vous êtes le premier propriétaire de cette moto. Sinon, ajoutez le nombre de propriétaires avant vous."
            }
end

app/controllers/cycles_controller.rb
class CyclesController < ApplicationController
  def index
    @cycles = Cycle.all
  end

  def show
    @cycle = Cycle.find(params[:id])
  end

  def new
    @cycle = Cycle.new
  end

  def create
    @cycle = Cycle.new(cycle_params)
    @cycle.user = current_user
    if @cycle.save
      redirect_to cycle_path(@cycle)
    else
      render :new
    end
  end

  def edit
    @cycle = Cycle.find(params[:id])
  end

  def update
    @cycle = Cycle.find(params[:id])
    if @cycle.update(cycle_params)
      redirect_to cycle_path(@cycle)
    else
      render :edit
    end
  end

  def destroy
    @cycle = Cycle.find(params[:id])
    @cycle.delete
    redirect_to cycles_path, status: :see_other
  end

  private

  def cycle_params
    params.require(:cycle).permit(
      :title,
      :description,
      :color,
      :general_state,
      :location,
      :price,
      :license_id,
      :brand_id,
      :model_id,
      :nb_of_owners,
      :tires_state,
      :battery_soh,
      :maintenances,
      :kilometrage,
      :release_date,
      :user_combined_range
    )
  end
end

app/views/cycles/edit.html.erb
<h1>Cycle#edit</h1>
<p>Find me in app/views/cycle/edit.html.erb</p>

<%= simple_form_for @cycle do |f| %>
  <%= f.input :title %>
  <%= f.input :description %>
  <%= f.input :color %>
  <%= f.input :general_state %>
  <%= f.input :location %>
  <%= f.input :price %>
  <%= f.submit "Update", class: "btn btn-primary" %>
<% end %>

app/views/cycles/index.html.erb
<h1>Cycle#index</h1>
<p>Find me in app/views/cycle/index.html.erb</p>

<ul>
  <% @cycles.each do |cycle| %>
    <li>
      <%= link_to cycle.title, cycle_path(cycle) %> : <%= cycle.description %> - <%= cycle.color %> - <%= cycle.general_state %> - <%= cycle.location %> - <%= cycle.price %></p>
    </li>
  <% end %>
</ul>

<p><%= link_to "New", new_cycle_path, class: "btn btn-primary" %></p>

app/views/cycles/new.html.erb
<h1>Cycle#new</h1>
<p>Find me in app/views/cycle/new.html.erb</p>

<%= simple_form_for @cycle do |f| %>
  <%= f.input :title %>
  <%= f.input :description %>
  <%= f.association :brand %>
  <%= f.association :model %>
  <%= f.association :license %>
  <%= f.input :color %>
  <%= f.input :general_state %>
  <%= f.input :location %>
  <%= f.input :price %>
  <%= f.input :nb_of_owners %>
  <%= f.input :tires_state %>
  <%= f.input :battery_soh %>
  <%= f.input :maintenances %>
  <%= f.input :kilometrage %>
  <%= f.input :release_date %>
  <%= f.input :user_combined_range %>
  <%= f.submit "Submit", class: "btn btn-primary" %>
<% end %>

app/views/cycles/show.html.erb
<h1><%= @cycle.title %></h1>
<p><%= @cycle.description %></p>

<ul>
  <li><%= link_to @cycle.brand.title, brand_path(@cycle.brand) %></li>
  <li><%= link_to @cycle.model.title, model_path(@cycle.model) %></li>
  <li><%= link_to @cycle.license.title, license_path(@cycle.license) %></li>
  <li><%= @cycle.color %></li>
  <li><%= @cycle.general_state %></li>
  <li><%= @cycle.location %></li>
  <li><%= @cycle.price %></li>
  <li>Publié par : <%= @cycle.user.first_name %></li>
</ul>

<p><%= link_to "< Back", cycles_path, class: "btn btn-secondary py-2" %></p>
<p><%= link_to "Edit", edit_cycle_path, class: "btn btn-info py-2" %></p>
<%# Destroy works but turbo_confirm doesnt %>
<p><%= button_to "Destroy", cycle_path(@cycle), method: :delete, data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                  } %></p>