config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Defines the root path route ("/")
  root to: "cycles#index"
  # Defines custom routes
  resources :cycles
  resources :models, only: [
    :show,
    :new,
    :create,
    :edit,
    :update,
    :destroy
  ]
  resources :brands, only: [
    :show,
    :new,
    :create,
    :edit,
    :update,
    :destroy
  ]
  resources :licenses, only: [
    :show,
    :new,
    :create,
    :edit,
    :update,
    :destroy
  ]
end

app/models/brand.rb
class Brand < ApplicationRecord
  has_many :cycles
end

app/controllers/brands_controller.rb
class BrandsController < ApplicationController
  def show
    @brand = Brand.find(params[:id])
  end

  def new
    @brand = Brand.new
  end

  def create
    @brand = Brand.new(brand_params)
    if @brand.save
      redirect_to brand_path(@brand)
    else
      render :new
    end
  end

  def edit
    @brand = Brand.find(params[:id])
  end

  def update
    @brand = Brand.find(params[:id])
    if @brand.update(brand_params)
      redirect_to brand_path(@brand)
    else
      render :edit
    end
  end

  def destroy
    @brand = Brand.find(params[:id])
    @brand.delete
    redirect_to cycles_path, status: :see_other
  end

  private

  def brand_params
    params.require(:brand).permit(
      :title,
      :description
    )
  end
end

app/views/brands/edit.html.erb
<h1>Brand#edit</h1>
<p>Admin view</p>

<%= simple_form_for @brand do |f| %>
  <%= f.input :title %>
  <%= f.input :description %>
  <%= f.submit "Update", class: "btn btn-primary" %>
<% end %>

app/views/brands/new.html.erb
<h1>Brand#new</h1>
<p>Admin view</p>

<%= simple_form_for @brand do |f| %>
  <%= f.input :title %>
  <%= f.input :description %>
  <%= f.submit "Submit", class: "btn btn-primary" %>
<% end %>

app/views/brands/show.html.erb
<h1><%= @brand.title %></h1>
<p><%= @brand.description %></p>

<ul>
  <% @brand.cycles.each do |cycle| %>
    <li>
      <%= link_to cycle.title, cycle_path(cycle) %> : <%= cycle.description %> - <%= cycle.color %> - <%= cycle.general_state %> - <%= cycle.location %> - <%= cycle.price %></p>
    </li>
  <% end %>
</ul>

<p><%= link_to "< Back", cycles_path, class: "btn btn-secondary py-2" %></p>
<p><%= link_to "Edit", edit_brand_path, class: "btn btn-info py-2" %></p>
<%# Destroy works but turbo_confirm doesnt %>
<p><%= button_to "Destroy", brand_path(@brand), method: :delete, data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                  } %></p>